### ISSUE TITLE
tsconfig base path issues

### ISSUE THREAD

**Issue by jcarruo** [ivogabe/gulp-typescript#253]
G'day

I'm using gulp-typescript with a tsconfig file and am having trouble with the base path in the output directory.   

**My source is organised as follows:**
src
-- folder 1
---- file1.ts
-- folder 2
---- file 2.ts

**I'm using the following:**

    var tsProject = typescript.createProject('tsconfig.json');
    var tsresult =  tsProject.src()
        .pipe(sourcemaps.init())
        .pipe(typescript(tsProject));
                
     return tsresult.js
        .pipe(sourcemaps.write())
        .pipe(gulp.dest('./dist')); 

**tsconfig is:**

    {
      "compilerOptions": {
        "noImplicitAny": false,
        "noEmitOnError": true,
        "removeComments": false,
        "sourceMap": true,
        "target": "es5",
        "module": "system",
        "experimentalDecorators": true
      },
      "exclude": [
        "node_modules",
        "jspm_packages"
      ]
    }

**my output is:**
dist
--src
---- folder 1
------ file1.ts
---- folder 2
------ file 2.ts

I'd like to get rid of the src folder when it is piped to the dist folder so that folder 1 & folder 2 are direct children of dist - I can't seem to crack it!

Any pointers would be great!

**Comment by ivogabe** [comment]
Can you set the `rootDir` option in your tsconfig file? See #240 for more details.

**Comment by jcarruo** [comment]
Thanks mate;  will give this a whirl, sounds like it'll do the trick. 

-----Original Message-----

**Comment by ivogabe** [comment]
@jcarruo Did `rootDir` fix it?

**Comment by jcarruo** [comment]
Nope it didn't. When adding "rootDir": "src" the task fails as it no longer finds the typescript definitions. 

-----Original Message-----

**Comment by tolemac** [comment]
The same issue here.

Readme says that `rootDir` is not supported, use gulp.src() instead: 
````
rootDir - Use base option of gulp.src() instead.
````

But when use `tsconfig.json` I can't use gulp.src() and I can't use `{base: "baseDir"}` option.

**Comment by jcarruo** [comment]
I've got a work around you might be able to rework to suit your needs. Will pass it on in the morning. 

-----Original Message-----

**Comment by jcarruo** [comment]
As promised:

 

var tsProject = typescript.createProject('tsconfig.json');    

    return gulp.src(['./src/**/*.ts', './typings/**/*.d.ts'], { base: './src' })                     

            .pipe(typescript(tsProject))

            .pipe(gulp.dest('./dist'));

**Comment by tolemac** [comment]
Thanks, I will test.

**Comment by landed1** [comment]
I am also here :(
no matter where I specify the destination the folder tree is created that mimics the src tree - I want to do a clean copy to a folder that I specify. I also think the config should be in the root of the project with the other config files its just correct :P
I have tried to play with the root directory setting but then nothing is output and the transpiler takes 38ms compared to the 4+ seconds....
Is this really the future of js development  where i have to wait 4s after a js edit ?

**Comment by landed1** [comment]
ok this finally works for me 
`{
  "compilerOptions": {
    "target": "ES5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "rootDir": "src/app/ts"
  },
  "exclude": [
    "node_modules"
  ]
}`

now src/app/ and ts folders are not created. Now the files go in the destination as expected.
Hope this helps.

**Comment by landed1** [comment]
interesting also that this has really sped up the transpilation but it is still more than 2seconds and we are talking about the two quickstart files on the Angular 2 getting started page...thats a worry.

**Comment by ivogabe** [comment]
The implementation of `tsProject.src` had a bug. With #276, setting rootDir isn't necessary any more, and typings are still found when you set rootDir. Can you test wether that's working in your projects? You can install it with:
```
npm install ivogabe/gulp-typescript#tsconfig-files
```

@landed1 I'm not sure why that's happening. Maybe some extra files inside `node_modules` are resolved in the second case, which increase compilation time. If compilation time is a problem to you, you can use incremental compilation or `isolatedModules`.

**Comment by symbyte** [comment]
I can confirm that I am still seeing this issue as of the 2.11.0 release (that includes #276). The strange thing is that it only happens when I have a certain character count across the files that are being compiled i.e. if I have the following source file structure:

```
src
----dir1
--------file1.ts
--------file2.ts
----dir2
--------file3.ts
--------file4.ts
--------file5.ts
----file6.ts
```
I will get the undesired result:

```
dist 
----src
--------dir1
------------file1.js
------------file2.js
--------dir2
------------file3.js
------------file4.js
------------file5.js
--------file6.js
```

But if I delete, say, file5.ts, I get the desired result of: 

```
dist
----dir1
--------file1.js
--------file2.js
----dir2
--------file3.js
--------file4.js
----file6.js

**Comment by ivogabe** [comment]
@symbyte I cannot reproduce that. Can you create an example that reproduces this and upload it to GitHub?

**Comment by lmjohansen** [comment]
Same thing here with gulp-typescript@2.12.1
Removing some files fixes it like @symbyte explained ?

**Comment by ivogabe** [comment]
@lmjohansen Can you share your project?

**Comment by lmjohansen** [comment]
[rep](https://github.com/lmjohansen/gts)

When i add the typedef files to tsconfig.json it creates the dist-app-src-app folder structure...

**Comment by lmjohansen** [comment]
"outDir": "dist/app" ---> "outDir": "dist"
and adding "rootDir":"src/app"

seems to solve the issue.

**Comment by ivogabe** [comment]
@lmjohansen thanks, I hope to investigate it next week.

**Comment by ivogabe** [comment]
Thanks to @lmjohansen, I could find the culprit. Definition files (`.d.ts`) should not be used to calculate the base directory, but they were used. The issue should be fixed in the master.

**Comment by unhealthy** [comment]
Actually, I still meet this problem.
My project folder looks like this.
```
src\
|-index.ts
tsconfig.json
```
In my tsconfig.json I have set `rootDir:'src'`
My gulpfile.js looks like this:
```javascript
gulp.task('build',  () => {
    return tsProject.src()
        .pipe(ts(tsProject))
        .pipe(gulp.dest('dist'));
});
```

The output in `dist`:
```
dist\
|-src\
|--index.js
```
But what I want is:
```
dist\
|-index.js
```

I have read the issue #240 . But I don't plan to put my `tsconfig.json` under the `src/` folder because I think it should be placed in the root of the project.

I now use the workaround method presented by @jcarruo 
```javascript
return gulp.src(['./src/**/*.ts', './typings/**/*.d.ts'], { base: './src' })                     

        .pipe(typescript(tsProject))

        .pipe(gulp.dest('./dist'));
```

Is this issue already fix? Or just I miss something.

**Comment by aravindanve** [comment]
Hi, I had the same problem. In my `tsconfig.json` I kept the `rootDir`option and removed the `outDir` option. Instead I'm using the `gulp.dest` function to redirect my output to my `dist` directory.

My files look like this:

**tsconfig.json**
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "rootDir": "src"
  }
}
```

**gulpfile.js**
```javascript
var tsProject = ts.createProject("tsconfig.json");

gulp.task('ts', function () {
    return tsProject.src()
        .pipe(ts(tsProject))
        .js.pipe(gulp.dest('dist'));
});
```
This fixed it for me. Now my output is written directly under `dist` like this:

```
dist/
|---app/
|   |---app.component.js
|   +--- ...
+---main.js

I hope this helps.

**Comment by unhealthy** [comment]
it's weird. Today I change the code back to `tsProject.src()` without any other modification, and then the output just works in the right way.
I don't know why, but it just works.

**Comment by ivogabe** [comment]
Thanks for reporting, this appears to be a regression in 2.14.0, caused by the new implementation of `tsProject.src()` (98eca4ab34cb02e54589e40e9871cda59dce36cb). Fixed in d04b0ad01a76798aec0f50cea1aabdfb96dd0724, tests in d0ce54321d5b56d158003fe8dbd978be78ddaa97
