### ISSUE TITLE
Duplicate source in path

### ISSUE THREAD

**Issue by sebastianwahn** [ivogabe/gulp-typescript#307]
Debug information: 
sourceRoot = "/pathToProject/Project/source/"
sources = ["source/controllers/SchemaController.ts"]
Could not find input file /pathToProject/project/source/source/models/IModel.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues

**Expected behavior:**
In gulp-typescript 2.11.0 it compiles properly

**Actual behavior:**
In gulp-typescript 2.12.1 the path is decorated with source another time

**Your gulpfile:**

*Include your gulpfile, or only the related task (with `ts.createProject`).*
```javascript
// gulp.sourceDir evaluates to ./source
var sourceDir = path.join(__dirname, config.get('gulp.sourceDir'));

gulp.task('compile', function() {
    var tsResult = gulp.src(sourceDir + '/**/*.ts')
        .pipe(ts(tsProject));
    return tsResult.js
        .pipe(sourcemaps.write())
        .pipe(gulp.dest(buildDestination));
});
```

**Comment by ivogabe** [comment]
How did you define tsProject? And can you post your tsconfig file if present?

**Comment by sebastianwahn** [comment]
```
var tsProject = ts.createProject(config.get('gulp.tsOptions'));
```

config:
```
...
"tsOptions": {
      "sortOutput": true
}
...
```

**Comment by ivogabe** [comment]
What happens when you remove the sortOutput option? What is your directory structure and what is the value of 'gulp.sourceDir'?

**Comment by sebastianwahn** [comment]
When removing `"sortOutput": true`, then the same errors occur.

`gulp.sourceDir` evaluates to `./source`

I noticed, that even node_modules are loaded from source:

Debug information: 
sourceRoot = "/pathToProject/Project/source/"
sources = ["node_modules/json-schema-to-mongoose/lib/json-schema.ts"]
Could not find input file /pathToProject/Project/source/node_modules/json-schema-to-mongoose/index.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues

Folder structure is 
sources: /pathToProject/Project/source
tests: /pathToProject/Project/test
node_modules: /pathToProject/Project/node_modules
gulp script: /pathToProject/Project/gulp.js

**Comment by falsandtru** [comment]
I saw this problem on v2.13.1. v2.13.0 works fine, but next version is not.

**Comment by ivogabe** [comment]
@falsandtru can you share your project?

**Comment by falsandtru** [comment]
@ivogabe here is that error log.

https://travis-ci.org/falsandtru/arch-stream/builds/128067953#L1196

**Comment by ivogabe** [comment]
Thanks, I think that I have fixed it with 0aad4f744004c8051572dd95516ce25e69cb8c38. Can you verify that?

**Comment by falsandtru** [comment]
I tried on master. Input file paths are fixed, but output paths are not. In my project, expect output path is `./dist/<package>.js`, but actual path is `./<package>.js`.

**Comment by falsandtru** [comment]
repro

0. Checkout my project.
0. npm i
0. rm -rf node_modules/gulp-typescript/
0. git clone https://github.com/ivogabe/gulp-typescript.git node_modules/gulp-typescript
0. cd node_modules/gulp-typescript/
0. npm i --production
0. cd -
0. gulp build

**Comment by ivogabe** [comment]
@falsandtru That should now be fixed with 9859e4795337da6b490a2c7fbb87565b59a42dd8.

**Comment by falsandtru** [comment]
@ivogabe It works fine! Thanks.

**Comment by maximedupre** [comment]
@ivogabe 

I'm on `v2.13.3` and I have the same problem. I get multiple error messages such as 

    Could not find input file ~/Desktop/Dropbox/Projects/project/front-end/front-end/analytics.ts. This is probably an issue of gulp-typescript.
    Please report it at https://github.com/ivogabe/gulp-typescript/issues
    Debug information: 
    sourceRoot = "~/Desktop/Dropbox/Projects/project/"
    sources = ["front-end/front-end/analytics.ts"
  
or

    Could not find input file ~/Desktop/Dropbox/Projects/project/front-end/________________empty.ts. This is probably an issue of gulp-typescript.
    Please report it at https://github.com/ivogabe/gulp-typescript/issues
    Debug information: 
    sourceRoot = "~/Desktop/Dropbox/Projects/project/"
    sources = ["front-end/________________empty.ts"]

This is my `tsconfig.json`:

    {
    	"compilerOptions": {
    		"rootDir": "./",
    		"target": "es5",
    		"module": "system",
    		"moduleResolution": "node",
        	"emitDecoratorMetadata": true,
        	"experimentalDecorators": true,
    		"noImplicitAny": true
    	},
    	"exclude": [
	    	"node_modules",
	    	"front-end/node_modules",
		    "typings/main",
    	    "typings/main.d.ts"
	    ]
    }

**Comment by ivogabe** [comment]
@maximedupre Can you share your full project? What happens when you remove `rootDir`?

**Comment by maximedupre** [comment]
I have reverted to `v2.13.3` for additional tests.

When I first launch the gulp task, the errors mentioned in my previous comment don't appear (although nothing is transpiled), but as soon as I modify a file that is being watched and that the task is executed again, the error messages appear.

My set for `gulp-typescript` looks like this:
   
    let gulp = require('gulp');
    let typescript = require('gulp-typescript');
    let typescriptProject = typescript.createProject('tsconfig.json');    

    let compileToJs = function() {
	    let toPipe = typescript(typescriptProject);
	    let typescriptResult = typescriptProject.src().pipe(toPipe);
	    let gulpDestination = gulp.dest('.');

    	return typescriptResult.js.pipe(gulpDestination);
    }
    let watchForCompiliation = function() {
        gulp.watch('**/*.ts', { cwd: './' }, ['typescript']);
    }
    
    gulp.task('default', ['watchForCompiliation']);
    gulp.task('typescript', compileToJs);
    gulp.task('watchForCompiliation', ['typescript'], watchForCompiliation);

If I remove `rootDir` from my `tsconfig.json` as you suggested, there are no more errors and the transpilation does occur, but then the `.js` are all outputted at `/` instead of being outputted as a sibling to their respective `.ts`.

**Comment by ivogabe** [comment]
@maximedupre Thanks for the details, I could reproduce it and it should be fixed with https://github.com/ivogabe/gulp-typescript/commit/d2e0054e52d505c8031f6c1854fa476b19c74e3c. I've released the fix as 2.13.4

**Comment by maximedupre** [comment]
@ivogabe I confirm that the bug has been fixed. I think you can close this issue. Thanks!

**Comment by ivogabe** [comment]
@sebastianwahn Has this issue been solved for you too in the latest version? Or do you still get errors?

**Comment by maximedupre** [comment]
Actually, I still get an error, but at least this time it doesn't make my gulp task fail. My configs are the same as the one posted I previously, but the logs that I'm posting are from my production server as oppose to my dev server (although I also get this error on my dev server) because I wanted to take the opportunity to point to another bug that only occurs on my prod server.

The following error is similar to the issue that I posted previously (occurs both on dev and prod servers):

    Could not find input file /app/________________empty.ts. This is probably an issue of gulp-typescript.
    Please report it at https://github.com/ivogabe/gulp-typescript/issues
    Debug information: 
    sourceRoot = "/app/"
    sources = ["________________empty.ts"]

Additionally, on my prod server only, it seems that it's trying to transpile files that I have excluded (see my `tsconfig.json` above):

    /app/front-end/node_modules/@angular/common/src/directives/ng_class.d.ts(72,35): error TS2304: Cannot find name 'Set'.
    /app/front-end/node_modules/@angular/common/src/facade/async.d.ts(27,33): error TS2304: Cannot find name 'Promise'.
    /app/front-end/node_modules/@angular/common/src/facade/async.d.ts(28,45): error TS2304: Cannot find name 'Promise'.
    /app/front-end/node_modules/@angular/common/src/facade/lang.d.ts(4,17): error TS2304: Cannot find name 'Map'.
    /app/front-end/node_modules/@angular/common/src/facade/lang.d.ts(5,17): error TS2304: Cannot find name 'Set'.
    /app/front-end/node_modules/@angular/common/src/facade/lang.d.ts(70,59): error TS2304: Cannot find name 'Map'.
    ...

Note that my `tsconfig.json` is located at `/app` on my prod server.

**Comment by ivogabe** [comment]
@maximedupre Could you create a small example that reproduces this?

> Additionally, on my prod server only, it seems that it's trying to transpile files that I have excluded (see my `tsconfig.json` above):

Files that are referenced are processed even when they are excluded in tsconfig.json, the config file only excludes them as root files. So I don't think that's a bug, but you could compare that with `tsc` to check that.

**Comment by maximedupre** [comment]
#342 has the exact same problem, his project will most likely be able to reproduce that.

As for the second "bug", you are right and it has probably nothing to do with `gulp-typescript`. I will do some experimentations and if I find out that it's a `gulp-typescript` bug, I will create an appropriate ticket.

**Comment by maximedupre** [comment]
@ivogabe I added you as a collaborator to my private repo so that you can make some tests. Run `npm run gulp` and start modifying some files, it should compile each time and you should get the error after a short period of time.

**Comment by ivogabe** [comment]
@maximedupre Thanks, I could reproduce it. It only happens when a new compilation is triggered, with changed files and without `out` or `outFile`. Then the result from the previous compilation is reused, but somehow that error is still shown. I'll work on a fix.

**Comment by bzums** [comment]
Any progress here? Having the same issue:
`gulp.watch([PATHS.src, PATHS.index], ['watch:dev']);`

Funny enough, the error only occurs when I change the file behind `PATHS.index` which is the index.html, when changing something in `PATHS.src` everything works fine.

Directory structure is:
```
project/
|- gulpfile.js
|- src/
    |- index.html
    |- app/
        | - **/*.ts
```

Exact error:
```
Could not find input file /Users/.../frontend/src/src/app/domain/shop.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "/Users/.../frontend/src/"
sources = ["src/app/domain/shop.ts"]
Could not find input file /Users/.../frontend/src/src/app/domain/country.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "/Users/.../frontend/src/"
...
...
... goes on for a lot of files...
```

**Comment by ivogabe** [comment]
@bzums It should be fixed for most configurations now, though for yours apparently not. Can you share your project? Is it somewhere on GitHub? You may mail it as a zip file privately too.

**Comment by bzums** [comment]
@ivogabe I just realised that it the compilation actually working, the error is just thrown nevertheless. Still interested in the project or is that known?

**Comment by ivogabe** [comment]
Yes, as a lot of false messages is not desired, even when the compilation works.

**Comment by bzums** [comment]
@ivogabe I figured it out, maybe a known problem?!

My old gulp setup was roughly like this:
```
var tsProject = typescript.createProject('tsconfig.json');
...
gulp.watch([...], ['watch:dev']);
```
and `watch:dev` does something like:
```
  return gulp
    .src(src)
    .pipe(typescript(tsProject))
    .pipe(gulp.dest(destination));
```

The fix is to do `var tsProject = typescript.createProject('tsconfig.json');` before each compile...

It seems strange to me that one has to "reload" the config for each compile...if its intended this should be documented somewhere I guess.

Anyway, thanks for the support!

**Comment by ivogabe** [comment]
That's absolutely not desired. The idea of a tsProject is that it can be reused and reduce the compilation time.  Can you share your project?

**Comment by supamax** [comment]
The same for me. Reproduced only in gulp.watch task.

Could not find input file G:\Git\example\source\app\app\iAppConfiguration.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "G:/Git/example/source/app/"
sources = ["app\\iAppConfiguration.ts"]

**Comment by ivogabe** [comment]
@supamax Can you share your project?

**Comment by spali** [comment]
I think I can reproduce it very simple with the mgechev/angular2-seed project as described with my comment in issue mgechev/angular2-seed#1145.
owner of the angular2-seed project directed me to this issue and it probably is the same.
I'm don't know whats going on under the hood, so I can't really isolate the problem better.
But hope my reproducible test case can help.

test-case copy from the original issue:
1. `git clone https://github.com/mgechev/angular2-seed.git`
2. `cd .\angular2-seed`
3. `npm install`
4. `npm start` -> **no errors**
5. touched file `app.module.ts` without changes -> **reloaded without errors**
6. killed npm process
7. `npm install angular2-busy --save`
8. modified `app.module.ts` (adding import of service and added to providers):
```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { APP_BASE_HREF } from '@angular/common';
import { RouterModule } from '@angular/router';
import { HttpModule } from '@angular/http';
import { AppComponent } from './app.component';
import { routes } from './app.routes';

import { AboutModule } from './+about/about.module';
import { HomeModule } from './+home/home.module';
import { SharedModule } from './shared/shared.module';
import { BusyService } from 'angular2-busy';

@NgModule({
  imports: [BrowserModule, HttpModule, RouterModule.forRoot(routes), AboutModule, HomeModule, SharedModule.forRoot()],
  declarations: [AppComponent],
  providers: [{
    provide: APP_BASE_HREF,
    useValue: '<%= APP_BASE %>'
  },
  BusyService],
  bootstrap: [AppComponent]

})

export class AppModule { }
```
8. `npm start` -> **no errors**
9. touched file `app.module.ts` without changes -> r**eloaded with errors**:
```
[13:33:29] Starting 'build.js.dev'...
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\app\shared\name-list\name-list.service.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\app\\shared\\name-list\\name-list.service.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\app\shared\name-list\index.ts. This is probably an issue of gulp-typescript.

Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\app\\shared\\name-list\\index.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\app\shared\navbar\navbar.component.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\app\\shared\\navbar\\navbar.component.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\app\shared\navbar\index.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\app\\shared\\navbar\\index.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\app\shared\toolbar\toolbar.component.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\app\\shared\\toolbar\\toolbar.component.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\app\shared\toolbar\index.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\app\\shared\\toolbar\\index.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\app\shared\config\env.config.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\app\\shared\\config\\env.config.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\app\shared\index.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\app\\shared\\index.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\app\app.component.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\app\\app.component.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\app\+about\about.component.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\app\\+about\\about.component.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\app\+about\about.routes.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\app\\+about\\about.routes.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\app\+about\index.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\app\\+about\\index.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\app\+home\home.component.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\app\\+home\\home.component.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\app\+home\home.routes.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\app\\+home\\home.routes.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\app\+home\index.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\app\\+home\\index.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\app\app.routes.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\app\\app.routes.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\app\+about\about.module.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\app\\+about\\about.module.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\app\shared\shared.module.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\app\\shared\\shared.module.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\app\+home\home.module.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\app\\+home\\home.module.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\node_modules\angular2-busy\index.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["node_modules\\angular2-busy\\index.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\app\app.module.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\app\\app.module.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\app\hot_loader_main.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\app\\hot_loader_main.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\app\main.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\app\\main.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\testing\router\mock-location-strategy.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\testing\\router\\mock-location-strategy.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\testing\router\router-testing-providers.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\testing\\router\\router-testing-providers.ts"]
Could not find input file C:\Data\_git\irt-web\test\angular2-seed\src\client\src\client\________________empty.ts. This is probably an issue of gulp-typescript.
Please report it at https://github.com/ivogabe/gulp-typescript/issues
Debug information:
sourceRoot = "C:/Data/_git/irt-web/test/angular2-seed/src/client/"
sources = ["src\\client\\________________empty.ts"]
[13:33:29] Finished 'build.js.dev' after 80 ms
```

**Comment by rousdan** [comment]
I'm having the same issue

**Comment by hoangnguyenba** [comment]
I'm having the same issue :(
My project is using angular2-seed. Just update to newest version ( rc6 ) and get a lot of errors like this.
But it only happen when I change html file, it's working when I change ts file.

**Comment by TianCNCA** [comment]
Having the same issue using angular2-seed. Symptoms and reproduce steps are the same as @spali

**Comment by hoangnguyenba** [comment]
I deleted node_packages and typings, then reinstall. It's working.

**Comment by ivogabe** [comment]
This should happen any more in version 3 of gulp-typescript, since the logic where paths are constructed has been replaced.

**Comment by webia1** [comment]
Where is the version 3? Npm still installs v2.13.6. Please Feedback, thank you!
